export const currencies = [
    {
        "key" : "90",
        "name":"Bitcoin(BTC)",
        "sortName":"BTC",
        "selected": false,
        "amount" : 0.5,
        "amountUsd": 3254.24,
        "rate" : 6508.48,
        "image":require('../images/bitcoin.png'),
        "isAdded": false,
    },
    {
        "key" : "2",
        "name":"Ethereum(ETH)",
        "sortName":"ETH",
        "selected": false,
        "amount" : 3.26,
        "amountUsd": 667.03,
        "rate" : 204.61,
        "image": require('../images/arrow_pyramid.png'),
        "isAdded": false,
    },
    {
        "key" : "3",
        "name":"Bitcoin Cash(BCH)",
        "sortName":"BCH",
        "selected": false,
        "amount" : 9.59,
        "amountUsd": 4266.34,
        "rate" : 444.88,
        "image": require('../images/bch.png'),
        "isAdded": false,
    },
    {
        "key" : "4",
        "name":"Litecoin(LTC)",
        "sortName":"LTC",
        "amount" : 10,
        "amountUsd": 527.1,
        "rate" : 52.71,
        "selected": false,
        "image": require('../images/temporary_image/litecoin.png'),
        "isAdded": false,
    },
    {
        "key" : "5",
        "name":"Dash(DASH)",
        "sortName":"DASH",
        "amount" : 4.05,
        "amountUsd": 633.66,
        "rate" : 156.46,
        "selected": false,
        "image": require('../images/temporary_image/dash.png'),
        "isAdded": false,
    },
    {
        "key" : "6",
        "name":"Ethereum Classic(ETC)",
        "sortName":"ETC",
        "amount" : 20.50,
        "amountUsd": 200.69,
        "rate" : 9.79,
        "selected": false,
        "image": require('../images/temporary_image/ethereum_classic.png'),
        "isAdded": false,
    },
    {
        "key" : "7",
        "name":"ZCash(ZEC)",
        "sortName":"ZEC",
        "amount" : 15,
        "amountUsd": 1852.50,
        "rate" : 123.5,
        "selected": false,
        "image": require('../images/temporary_image/zcash.png'),
        "isAdded": false,
    },
    {
        "key" : "8",
        "name":"Doge(DOGE)",
        "sortName":"DOGE",
        "amount" : 50,
        "amountUsd": 0.2,
        "rate" : 0.004,
        "selected": false,
        "image": require('../images/temporary_image/doge.png'),
        "isAdded": false,
    },
    {
        "key" : "9",
        "name":"Ripple(XRP)",
        "sortName":"XRP",
        "amount" : 30,
        "amountUsd": 13.80,
        "rate" : 0.46,
        "selected": false,
        "image": require('../images/temporary_image/ripple.png'),
        "isAdded": false,
    },
    {
        "key" : "10",
        "name":"Eos(EOS)",
        "sortName":"EOS",
        "amount" : 8,
        "amountUsd": 43.20,
        "rate" : 5.40,
        "selected": false,
        "image": require('../images/temporary_image/eos.png'),
        "isAdded": false,
    },
    {
        "key" : "11",
        "name":"Tether(USDT)",
        "sortName":"USDT",
        "amount" : 90,
        "amountUsd": 89.10,
        "rate" : 0.99,
        "selected": false,
        "image": require('../images/temporary_image/tether.png'),
        "isAdded": false,
    },
    {
        "key" : "12",
        "name":"Cardano(ADA)",
        "sortName":"ADA",
        "amount" : 100,
        "amountUsd": 7.40,
        "rate" : 0.074,
        "selected": false,
        "image": require('../images/temporary_image/cardano.jpg'),
        "isAdded": false,
    }
    
]