export const icoList = [
    {
        key: 1,
        name: 'Blockchain.io',
        description: 'Your Gateway to the Internet of Value.',
        amountUsd: 34,
        amount: 20,
        image: require('../images/temporary_image/blockchain-io.jpg'),
    },
    {   
        key: 2,
        name: 'HetaChain',
        description: 'A Trendy Third Generation Blockchain Platform',
        amountUsd: 23,
        amount: 32,
        image: require('../images/temporary_image/hetachain.jpg'),
    },
    {
        key: 3,
        name: 'SilkChain',
        description: 'The First Blockchain Based Platform in Global.',
        amountUsd: 12,
        amount: 27,
        image: require('../images/temporary_image/silkchain.jpg'),
    },
    {
        key: 4,
        name: 'Infleum',
        description: 'INFLEUM is executed by ELSOLCOM, a company that specializes in growing start-up’s and SMEs. ELSOLCOM,',
        amountUsd: 21,
        amount: 12,
        image: require('../images/temporary_image/infleum.jpg'),
    },
    {
        key: 5,
        name: 'UniFox',
        description: 'Imagine MasterCard for Cryptocurrencies',
        amountUsd: 40,
        amount: 11,
        image: require('../images/temporary_image/unifox.jpg'),
    },
    {
        key: 6,
        name: 'ICOVO',
        description: 'ICO Platform Protecting Investors with DAICO.',
        amountUsd: 14,
        amount: 43,
        image: require('../images/temporary_image/icovo.jpg'),
    },
    {
        key: 7,
        name: 'Fiii',
        description: 'Making Cryptocurrencies Available To All',
        amountUsd: 10,
        amount: 33,
        image: require('../images/temporary_image/fiii.jpg'),
    },
    {
        key: 8,
        name: 'Kuende',
        description: 'Creating Real Life Experiences',
        amountUsd: 34,
        amount: 29,
        image: require('../images/temporary_image/kuende.jpg'),
    },
    {
        key: 9,
        name: 'Ternion',
        description: 'Hybrid Crypto Exchange With A Fiat Gateway',
        amountUsd: 39,
        amount: 19,
        image: require('../images/temporary_image/ternion.jpg'),
    },
    {
        key: 10,
        name: 'Bethereum',
        description: 'Award-Winning Social Betting Platform',
        amountUsd: 25,
        amount: 21,
        image: require('../images/temporary_image/bethereum.jpg'),
    },
]