export const walletsList = [
    {
        "key" :"5",
        "name":"dobi",
        "sortName":"DOB",
        "selected": false,
        "amount" : 1.434,
        "amountUsd": 3343,
        "rate" : 301,
        "image":require('../images/temporary_image/dobi.png'),
    },
    {
        "key" :"OKEX_INFO",
        "name":"okex",
        "selected": true,
        "createScreen":"createOkexConnection",
        "accountInfo":"ACCOUNT_INFO_OKEX",
        "amount" : 1.434,
        "amountUsd": 3343,
        "rate" : 301,
        "image":require('../images/temporary_image/okex.png'),
    },
    {
        "key" :"COINBASE_INFO",
        "name":"coinbase",
        "selected": true,
        "createScreen":"createCoinbaseConnection",
        "accountInfo":"ACCOUNT_INFO_COINBASE",
        "amount" : 1.434,
        "amountUsd": 3343,
        "rate" : 301,
        "image":require('../images/temporary_image/coinbase.png'),
    },
    {
        "key" :"KUCOIN_INFO",
        "name":"kucoin",
        "selected": true,
        "createScreen":"createKucoinConnection",
        "accountInfo":"ACCOUNT_INFO_KUCOIN",
        "amount" : 1.434,
        "amountUsd": 3343,
        "rate" : 301,
        "image":require('../images/temporary_image/kucoin.jpg'),
    },
    {
        "key" : "90",
        "name":"bithumb",
        "sortName":"BTC",
        "selected": false,
        "amount" : 1.434,
        "amountUsd": 3343,
        "rate" : 301,
        "image":require('../images/temporary_image/bithumb.png'),
    },
    {
        "key" : "BINANCE_INFO",
        "name":"binance",
        "sortName":"ETH",
        "selected": true,
        "createScreen":"createBinanceConnection",
        "accountInfo":"ACCOUNT_INFO_BINANCE",
        "amount" : 2.434,
        "amountUsd": 3333,
        "rate" : 401,
        "image": require('../images/temporary_image/binance.png')
    },
    {
        "key" : "3",
        "name":"upBit",
        "sortName":"BCH",
        "selected": false,
        "amount" : 4.434,
        "amountUsd": 43,
        "rate" : 1,
        "image": require('../images/temporary_image/upbit.png')
    },
    {
        "key" : "4",
        "name":"huobi",
        "sortName":"LTC",
        "amount" : 434,
        "amountUsd": 343,
        "rate" : 301,
        "selected": false,
        "image": require('../images/temporary_image/huobi.png')
    }    
]