# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'airWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for airWallet

  # pod ‘FBSDKLoginKit’
  # pod ‘TwitterKit’
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

 pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

 pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

 pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

#  pod 'TouchID', :path => '../node_modules/react-native-touch-id'
#pod 'react-native-simple-crypto', :path => '../node_modules/react-native-simple-crypto'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
        
    end
end

  target 'airWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'airWallet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for airWallet-tvOS

  target 'airWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
